package menus.components;

import amalgamation.Amalgamation;

/**
 *
 * @author Adam Meanor
 */
public class LevelPanel extends acomponent.AComponent {
    
    Amalgamation amalgamation;

    /**
     * Creates new form LevelPanel
     */
    public LevelPanel(Amalgamation amalgamation) {
        initComponents();
        this.amalgamation = amalgamation;
        this.displayLevel(amalgamation);
        this.displayExperience(amalgamation);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentLevelLabel = new javax.swing.JLabel();
        targetExperienceLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(204, 204, 204)));

        currentLevelLabel.setBackground(new java.awt.Color(255, 255, 255));
        currentLevelLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        currentLevelLabel.setText("jLabel1");

        targetExperienceLabel.setBackground(new java.awt.Color(255, 255, 255));
        targetExperienceLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        targetExperienceLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentLevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(targetExperienceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentLevelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(targetExperienceLabel)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentLevelLabel;
    private javax.swing.JLabel targetExperienceLabel;
    // End of variables declaration//GEN-END:variables

    private void displayLevel(Amalgamation amalgamtaion) {
        currentLevelLabel.setText("LV: " + amalgamation.getLevel());
    }
    
    private void displayExperience(Amalgamation amalgamation) {
        targetExperienceLabel.setText("<html>EXP to next level:<br>" + amalgamation.getTargetExperience() + "</html>");
    }

}
