package menus.components;

/**
 * A StausPanel displays the HealthBar, name, and level of an Amalgamation.
 * 
 * @author Caleb Rush
 */
public class StatusPanel extends acomponent.AComponent {
    
    /**
     * Creates new form StatusPanel
     */
    public StatusPanel() {
        initComponents();
    }
    
    /**
     * Animates the Health Bar to reflect the given change of health.
     * 
     * @param deltaHealth the amount to increase the health by. A negative value
     *                    will decrease the health
     */
    public void changeHealth(int deltaHealth) {
        Health.animateHealth(Health.getCurrentHealth() + deltaHealth).await();
    }
    
    /**
     * Returns the current health shown in the health bar.
     * 
     * @return the current health shown in the health bar
     */
    public int getHealth() {
        return Health.getCurrentHealth();
    }
    
    /**
     * Sets the Amalgamation whose info is displayed by the StatusPanel.
     * 
     * @param amal the Amalgamation whose info should be displayed by the
     *             StatusPanel.
     */
    public void setAmalgamation(amalgamation.Amalgamation amal) {
        // Set the values for the labels and health bar.
        Name.setText(amal.getName());
        Level.setText("LV: " + amal.getLevel());
        Health.setMaxHealth(amal.getHealth());
        Health.setCurrentHealth(amal.getCurrentHealth());
    }
    
    /**
     * Sets whether or not the health bar should display numbers.
     * 
     * @param displayNumbers true if numbers should be displayed, false if not.
     */
    public void setDisplayNumbers(boolean displayNumbers) {
        Health.setDisplayNumbers(displayNumbers);
    }
    
    // <editor-fold desc="GUI Code" defaultstate="collapsed">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Health = new menus.components.HealthBar();
        Name = new acomponent.ALabel();
        Level = new acomponent.ALabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout HealthLayout = new javax.swing.GroupLayout(Health);
        Health.setLayout(HealthLayout);
        HealthLayout.setHorizontalGroup(
            HealthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
        HealthLayout.setVerticalGroup(
            HealthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        Name.setBackground(new java.awt.Color(255, 255, 255));
        Name.setForeground(new java.awt.Color(244, 67, 54));
        Name.setText("Name");

        javax.swing.GroupLayout NameLayout = new javax.swing.GroupLayout(Name);
        Name.setLayout(NameLayout);
        NameLayout.setHorizontalGroup(
            NameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        NameLayout.setVerticalGroup(
            NameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        Level.setBackground(new java.awt.Color(255, 255, 255));
        Level.setForeground(new java.awt.Color(33, 150, 243));
        Level.setHorizontalAlignment(4);
        Level.setStretchImage(true);
        Level.setText("LV: 15");

        javax.swing.GroupLayout LevelLayout = new javax.swing.GroupLayout(Level);
        Level.setLayout(LevelLayout);
        LevelLayout.setHorizontalGroup(
            LevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        LevelLayout.setVerticalGroup(
            LevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Health, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(180, 180, 180)
                        .addComponent(Level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Health, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private menus.components.HealthBar Health;
    private acomponent.ALabel Level;
    private acomponent.ALabel Name;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
