/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amalgamation.parts;

/**
 *
 * @author aam5617
 */
public class PartListPanel extends javax.swing.JPanel {
    private Part[] parts;
    /**
     * Creates new form PartListPanel
     */
    public PartListPanel(int type) {
        initComponents();
        if (type == Parts.TYPE_ARM) {
            try {
                parts = amalgamation.parts.Parts.getArms(
                        amalgamation.parts.Parts.PARTS_RES_DIR);
            } catch (java.io.IOException e) {
                e.printStackTrace();
            } 
        }
        
        if (type == Parts.TYPE_BODY) {
            try {
                parts = amalgamation.parts.Parts.getBodies(
                        amalgamation.parts.Parts.PARTS_RES_DIR);
            } catch (java.io.IOException e) {
                e.printStackTrace();
            }
        }
            
        if (type == Parts.TYPE_LEG) {
            try {
                parts = amalgamation.parts.Parts.getLegs(
                        amalgamation.parts.Parts.PARTS_RES_DIR);
            } catch (java.io.IOException e) {
                e.printStackTrace();
            }
        }
            
            
        if (type == Parts.TYPE_HEAD) {
            try {
                parts = amalgamation.parts.Parts.getHeads(
                        amalgamation.parts.Parts.PARTS_RES_DIR);
            } catch (java.io.IOException e) {
                e.printStackTrace();
            }
        }
            
        PartPanel[] panels = new PartPanel[parts.length];
            
        for(int i = 0; i < parts.length; i++)
        {
            panels[i] = new PartPanel(parts[i]);
            ListPanel.add(panels[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(220, 550));
        setMinimumSize(new java.awt.Dimension(220, 550));
        setPreferredSize(new java.awt.Dimension(220, 550));

        ListPanel.setLayout(new javax.swing.BoxLayout(ListPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(ListPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String[] args) {
    javax.swing.JFrame window = new javax.swing.JFrame("Testing");
        window.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        window.add(new PartListPanel(Parts.TYPE_HEAD));
        window.pack();
        window.setLocationRelativeTo(null);
        window.setVisible(true);
}
}
