/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amalgamation.menus;

import amalgamation.Amalgamation;
import amalgamation.Amalgamations;

/**
 *
 * @author jjl5451
 */
public class AmalgamationPanel extends javax.swing.JPanel {

        // The body to test.
    private Amalgamation amal;
    // Image of the full body.
    private java.awt.Image image;
    // ImagePanel to draw the image.
    private Runnable clickAction;

    
    
    /**
     * Creates new form AmalgamationPanel
     */
    public AmalgamationPanel(Amalgamation amal) {
        initComponents();
        this.amal = amal;
       
  
    }
    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        // Draw the image scaled to the size of the panel.
        int width, height;
        if (amal.getFullImage().getWidth() >= amal.getFullImage().getHeight()) {
            width = getWidth();
            height = amal.getFullImage().getHeight() 
                    * width / amal.getFullImage().getWidth();
        }
        else {
            height = getHeight();
            width = amal.getFullImage().getWidth() 
                    * height / amal.getFullImage().getHeight();
        }
        g.drawImage(amal.getFullImage(), 
                getWidth() / 2 - width / 2, 
                getHeight() / 2 - height / 2,
                width,
                height,
                null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(350, 350));
        setMinimumSize(new java.awt.Dimension(350, 350));
        setPreferredSize(new java.awt.Dimension(350, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}



