package menus;

/**
 * The main menu of the game.
 * 
 * @author Caleb Rush
 */
public class MainMenu extends javax.swing.JPanel {
    // The currently selected Amalgamation.
    private amalgamation.Amalgamation amalgamation;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }
    
    // <editor-fold desc="GUI Variables" defaultstate="collapsed">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoPanel = new acomponent.AComponent();
        CreateButton = new acomponent.AButton();
        LoadButton = new acomponent.AButton();
        CampaignButton = new acomponent.AButton();
        NetworkButton = new acomponent.AButton();

        setBackground(new java.awt.Color(255, 255, 255));

        LogoPanel.setBackground(new java.awt.Color(255, 255, 255));
        LogoPanel.setImage("res/img/logo.png");
        LogoPanel.setStretchImage(true);

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        CreateButton.setBackground(new java.awt.Color(244, 67, 54));
        CreateButton.setActionListener(e -> {
            // Create a new Amalgamation.
            menus.components.AmalgamationCreatorDialog.create(null);
        });
        CreateButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        CreateButton.setText("Create");

        javax.swing.GroupLayout CreateButtonLayout = new javax.swing.GroupLayout(CreateButton);
        CreateButton.setLayout(CreateButtonLayout);
        CreateButtonLayout.setHorizontalGroup(
            CreateButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        CreateButtonLayout.setVerticalGroup(
            CreateButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        LoadButton.setBackground(new java.awt.Color(76, 175, 80));
        LoadButton.setActionListener(e -> {
            // Have the user choose an Amalgamation
            amalgamation = menus.components.AmalgamationDialog.showDialog(null);
        });
        LoadButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        LoadButton.setText("Load");

        javax.swing.GroupLayout LoadButtonLayout = new javax.swing.GroupLayout(LoadButton);
        LoadButton.setLayout(LoadButtonLayout);
        LoadButtonLayout.setHorizontalGroup(
            LoadButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        LoadButtonLayout.setVerticalGroup(
            LoadButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        CampaignButton.setBackground(new java.awt.Color(33, 150, 243));
        CampaignButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        CampaignButton.setText("Campaign");

        javax.swing.GroupLayout CampaignButtonLayout = new javax.swing.GroupLayout(CampaignButton);
        CampaignButton.setLayout(CampaignButtonLayout);
        CampaignButtonLayout.setHorizontalGroup(
            CampaignButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        CampaignButtonLayout.setVerticalGroup(
            CampaignButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        NetworkButton.setBackground(new java.awt.Color(66, 66, 66));
        NetworkButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        NetworkButton.setText("Network");

        javax.swing.GroupLayout NetworkButtonLayout = new javax.swing.GroupLayout(NetworkButton);
        NetworkButton.setLayout(NetworkButtonLayout);
        NetworkButtonLayout.setHorizontalGroup(
            NetworkButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        NetworkButtonLayout.setVerticalGroup(
            NetworkButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CampaignButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NetworkButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampaignButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NetworkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private acomponent.AButton CampaignButton;
    private acomponent.AButton CreateButton;
    private acomponent.AButton LoadButton;
    private acomponent.AComponent LogoPanel;
    private acomponent.AButton NetworkButton;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>

    public void enter() {
        LogoPanel.enter(LogoPanel.getX(), LogoPanel.getY(), 
                LogoPanel.getWidth(), LogoPanel.getHeight());
        CreateButton.enter(CreateButton.getX(), CreateButton.getY(),
                CreateButton.getWidth(), CreateButton.getHeight());
        LoadButton.enter(LoadButton.getX(), LoadButton.getY(),
                LoadButton.getWidth(), LoadButton.getHeight());
        CampaignButton.enter(CampaignButton.getX(), CampaignButton.getY(),
                CampaignButton.getWidth(), CampaignButton.getHeight());
        NetworkButton.enter(NetworkButton.getX(), NetworkButton.getY(),
                NetworkButton.getWidth(), NetworkButton.getHeight());
    }
    
    public static void main(String[] args) {
        javax.swing.JFrame window = new javax.swing.JFrame();
        window.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        
        MainMenu menu = new MainMenu();
        window.add(menu);
        
        window.pack();
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        
        menu.enter();
    }
}
